# Capstone/settings.py
"""
Django settings for Capstone project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from django.conf.global_settings import STATICFILES_DIRS
from django.core.asgi import get_asgi_application

PAYMONGO_SECRET_KEY = 'sk_test_QR6jF33RUJ5rhBfGiTirT6Ag'
PAYMONGO_PUBLIC_KEY = 'pk_test_y94mFUoDLXbD99SygpeHiUCq'

PAYMONGO_API_URL = 'https://api.paymongo.com/v1'
SITE_URL = 'http://127.0.0.1:8000'

PAYMONGO_GCASH_SOURCE_URL = 'https://api.paymongo.com/v1/sources'
PAYMONGO_GCASH_CHECKOUT_URL = 'https://api.paymongo.com/v1/checkout_sessions'

LOGIN_URL = 'food_establishment_login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kabsueatsdep@gmail.com'
EMAIL_HOST_PASSWORD = 'twkq psax xjgy xdvv'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = 'kabsueats_home'
LOGOUT_REDIRECT_URL = 'user_login_register'

GOOGLE_CLIENT_ID = '597255921135-n8g38r5u3p0u5akndenm5lltg4ikq3j5.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'
GOOGLE_REDIRECT_URI = 'https://34b987c61741.ngrok-free.app/accounts/google/callback'


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b$-7u%j-7cc_pbp!_penzpu(xd009$ro@=xf$89-mktoss=s-l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.11','192.168.1.5', 'localhost', '127.0.0.1', '192.168.254.120', '192.168.254.120', '10.136.92.88', '10.20.78.227', '192.168.254.125',".ngrok-free.app" , "192.168.254.131" ]
# b802-64-224-103-143.ngrok-free.app

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'webapp.apps.WebappConfig',
]
ASGI_APPLICATION = 'Capstone.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Capstone.urls'

import os # Add this line at the top of settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Added STATIC_ROOT to fix the ImproperlyConfigured error
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Used when running collectstatic

# Media files (Images, uploaded files)
# These settings are for handling uploaded files like images

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# your_project/settings.py

# Uncomment and add your ngrok domain here for CSRF trusted origins
# Use the exact ngrok domain from your error (e.g., 'https://b1381d33405c.ngrok-free.app')
# or use a wildcard 'https://*.ngrok-free.app' if it changes.
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://b1381d33405c.ngrok-free.app', # Example: replace with your actual ngrok URL
    'https://*.ngrok-free.app', # This wildcard covers all ngrok-free.app subdomains over HTTPS
]
# ===================================================================================
import os
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Secret Key and Debug mode
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-palitan-mo-ako-ng-bago-at-secure-key')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# SendGrid Settings
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
SENDER_EMAIL = os.getenv('SENDER_EMAIL')

# CvSU coordinates
CVSU_LATITUDE = os.getenv('CVSU_LATITUDE')
CVSU_LONGITUDE = os.getenv('CVSU_LONGITUDE')