# Capstone/settings.py
"""
Django settings for Capstone project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from django.conf.global_settings import STATICFILES_DIRS
from django.core.asgi import get_asgi_application
import os
from dotenv import load_dotenv
EMAIL_TIMEOUT = 10

# Base dir and load .env early so os.getenv picks up values from .env
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Secrets and config (loaded from environment/.env)
PAYMONGO_SECRET_KEY = os.getenv('PAYMONGO_SECRET_KEY', '')
PAYMONGO_PUBLIC_KEY = os.getenv('PAYMONGO_PUBLIC_KEY', '')

PAYMONGO_API_URL = os.getenv('PAYMONGO_API_URL', 'https://api.paymongo.com/v1')
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

PAYMONGO_GCASH_SOURCE_URL = os.getenv('PAYMONGO_GCASH_SOURCE_URL', 'https://api.paymongo.com/v1/sources')
PAYMONGO_GCASH_CHECKOUT_URL = os.getenv('PAYMONGO_GCASH_CHECKOUT_URL', 'https://api.paymongo.com/v1/checkout_sessions')

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'user_login_register'
LOGIN_REDIRECT_URL = 'kabsueats_home'
LOGOUT_REDIRECT_URL = 'user_login_register'

# Previous defaults (commented out for record)
# GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '597255921135-n8g38r5u3p0u5akndenm5lltg4ikq3j5.apps.googleusercontent.com')
# GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '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')

# Use environment values if present; fall back to the new provided keys
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY: SECRET_KEY and DEBUG are loaded from environment (see below)

# ALLOWED_HOSTS is computed later (after SECRET_KEY) to allow a DEBUG-aware fallback.

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'webapp.apps.WebappConfig',
]
ASGI_APPLICATION = 'Capstone.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Capstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Added STATIC_ROOT to fix the ImproperlyConfigured error
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Used when running collectstatic

# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (Images, uploaded files)
# These settings are for handling uploaded files like images

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# your_project/settings.py

# Uncomment and add your ngrok domain here for CSRF trusted origins
# Use the exact ngrok domain from your error (e.g., 'https://b1381d33405c.ngrok-free.app')
# or use a wildcard 'https://*.ngrok-free.app' if it changes.
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'https://kabsueats.onrender.com',
    # If you run the dev server on a different port or host, update SITE_URL above
]
# ===================================================================================
# Allow SITE_URL to be overridden from .env (so redirect URI matches runtime)
SITE_URL = os.getenv('SITE_URL', SITE_URL)

# Normalize SITE_URL: ensure scheme and remove trailing slash
if not SITE_URL.startswith(('http://', 'https://')):
    SITE_URL = 'http://' + SITE_URL
SITE_URL = SITE_URL.rstrip('/')

# Recompute Google redirect URI so it matches SITE_URL (useful when SITE_URL is set in .env)
GOOGLE_REDIRECT_URI = f"{SITE_URL}/accounts/google/callback"

# Debug: log and print effective redirect URI for development runs
try:
    import logging
    logging.getLogger('django').info(f"Effective GOOGLE_REDIRECT_URI set to: {GOOGLE_REDIRECT_URI}")
except Exception:
    pass
print(f"[DEBUG] Effective GOOGLE_REDIRECT_URI={GOOGLE_REDIRECT_URI}")

# Debug mode (read early so we can decide behavior for SECRET_KEY)
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Secret Key: must be provided via environment (.env). In production this must be set.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # development fallback (not secure) so local dev keeps working
        SECRET_KEY = 'django-insecure-dev-placeholder'
        import warnings
        warnings.warn('SECRET_KEY not set in environment — using insecure development fallback.', RuntimeWarning)
    else:
        raise RuntimeError('The SECRET_KEY environment variable is not set. Set it in .env or environment variables.')

# Compute ALLOWED_HOSTS here so we can include local hosts when DEBUG is True.
# Preference order: environment ALLOWED_HOSTS, then derive from SITE_URL, else empty.
raw_allowed = os.getenv('ALLOWED_HOSTS', '').strip()
if raw_allowed:
    ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(',') if h.strip()]
else:
    try:
        from urllib.parse import urlparse
        parsed = urlparse(SITE_URL)
        host_from_site = parsed.hostname
    except Exception:
        host_from_site = None
    ALLOWED_HOSTS = [host_from_site] if host_from_site else []

# Always allow local hosts when developing locally.
if DEBUG:
    for local_host in ('127.0.0.1', 'localhost'):
        if local_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(local_host)


# SendGrid Settings
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
SENDER_EMAIL = os.getenv('SENDER_EMAIL')

# CvSU coordinates
CVSU_LATITUDE = os.getenv('CVSU_LATITUDE')
CVSU_LONGITUDE = os.getenv('CVSU_LONGITUDE')

# ===================================================================================
# Auto-create superuser if environment variable is set
# This must be at the bottom because it requires Django setup
if os.environ.get("AUTO_CREATE_SUPERUSER") == "1":
    import django
    django.setup()
    from django.contrib.auth.models import User

    username = os.environ.get("DJANGO_SUPERUSER_USERNAME")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

    if username and password:
        if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(
                username=username,
                email=email or "",
                password=password
            )
            print("Superuser created successfully!")
        else:
            print("Superuser already exists.")
    else:
        print("Superuser environment variables not set.")