# Generated by Django 5.2.4 on 2025-07-14 13:53

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('price_range', models.CharField(choices=[('Affordable', 'Affordable'), ('Moderate', 'Moderate'), ('Expensive', 'Expensive')], max_length=10)),
                ('is_full', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('direction', models.CharField(blank=True, max_length=200, null=True)),
                ('access_code', models.CharField(default=webapp.models.generate_uuid, max_length=50, unique=True)),
                ('payment_methods', models.CharField(blank=True, help_text='e.g. Cash, GCash, Card', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='webapp.amenity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.category')),
                ('features', models.ManyToManyField(blank=True, to='webapp.feature')),
                ('open_days', models.ManyToManyField(blank=True, to='webapp.day')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEstablishmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=webapp.models.generate_uuid, max_length=50, unique=True)),
                ('food_establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.foodestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_top_seller', models.BooleanField(default=False)),
                ('top_seller_marked_at', models.DateTimeField(blank=True, null=True)),
                ('food_establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='webapp.foodestablishment')),
            ],
        ),
    ]
