# Generated by Django 5.2.4 on 2025-07-14 14:03

import django.db.models.deletion
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='is_full',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='uuid',
            field=models.CharField(default=webapp.models.generate_uuid, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='access_code',
            field=models.CharField(default=webapp.models.generate_access_code, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='direction',
            field=models.TextField(blank=True, default=1, help_text='Directions or landmarks to find the establishment.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments_images/'),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodestablishmentcode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='foodestablishmentcode',
            name='food_establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_code', to='webapp.foodestablishment'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='top_seller_marked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
