# Generated by Django 5.2.4 on 2026-02-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If False, hidden from customers.'),
        ),
    ]
