# Generated by Django 5.2.4 on 2026-02-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_create_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='is_active',
        ),
    ]
