# Generated by Django 5.2.4 on 2026-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_foodestablishment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Set to True after menu-item quantities have been deducted for this order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('to_pay', 'To Pay'), ('preparing', 'Preparing'), ('to_claim', 'To Claim'), ('completed', 'Completed'), ('order_received', 'Order Received'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='request', max_length=50),
        ),
    ]
