# Generated by Django 5.2.4 on 2026-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_order_add_cancelled_from_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_from_status',
            field=models.CharField(blank=True, default='', help_text='Status the order was in when owner rejected it (request/to_pay/to_claim).', max_length=20),
        ),
    ]
