# Generated by Django 5.2.4 on 2025-12-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_add_time_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Time when establishment closes (e.g., 10:00 PM)', null=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Time when establishment opens (e.g., 08:00 AM)', null=True),
        ),
    ]
