# Generated by Django 5.2.4 on 2026-03-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_add_is_deleted_to_ordernotification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordernotification',
            name='ordernotif_est_deleted_idx',
        ),
        migrations.RemoveField(
            model_name='ordernotification',
            name='is_deleted',
        ),
    ]
