# Generated by Django 5.2.4 on 2025-07-15 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_foodestablishment_is_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/'),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='payment_methods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodestablishmentcode',
            name='food_establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.foodestablishment'),
        ),
    ]
