# Generated by Claude - Add phone_number field to UserProfile
# Save this file as: webapp/migrations/0004_add_userprofile_phone_number.py
# (Change the number to match your latest migration + 1)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ⚠️ IMPORTANT: Change this to match your actual latest migration file
        # Example: if your last migration is 0003_auto_20250115.py, use:
        # ('webapp', '0003_auto_20250115'),
        ('webapp', '0001_initial'),  # CHANGE THIS LINE!
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]