# Generated by Django 5.2.4 on 2025-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_foodestablishment_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('payment_confirmed', 'Payment Confirmed'), ('order_cancelled', 'Order Cancelled'), ('order_completed', 'Order Completed')], default='new_order', max_length=50),
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['establishment', '-created_at'], name='webapp_orde_establi_ed92e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['is_read', '-created_at'], name='webapp_orde_is_read_2bc5ff_idx'),
        ),
    ]
