# Generated by Django 5.2.4 on 2026-04-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_ordernotification_ordernotif_est_deleted_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Set True for days the establishment is fully closed.')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='webapp.foodestablishment')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['day_of_week'],
                'unique_together': {('establishment', 'day_of_week')},
            },
        ),
    ]
