# Generated by Django 5.2.4 on 2026-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_foodestablishment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
