# Generated by Django 5.2.4 on 2026-04-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_businesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short display label, e.g. 'FB', 'Gmail', 'TikTok'", max_length=50)),
                ('value', models.CharField(help_text='Full URL (https://…) or e-mail address', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='webapp.foodestablishment')),
            ],
            options={
                'verbose_name': 'Contact / Social Link',
                'verbose_name_plural': 'Contact / Social Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
