# Generated by Django 5.2.4 on 2026-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_foodestablishmentcode_food_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='top_seller_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
