# Generated by Django 5.2.4 on 2026-04-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_establishmentcontactlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of selected add-on options [{id, name, additional_price}]'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note_to_establishment',
            field=models.TextField(blank=True, default='', help_text='Customer special request note for this item'),
        ),
        migrations.CreateModel(
            name='MenuItemAddOnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('max_choices', models.PositiveSmallIntegerField(default=1, help_text='0 = unlimited')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='webapp.menuitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemAddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='webapp.menuitemaddongroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
