# Generated by Django 5.2.4 on 2025-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_invitationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('invitation_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
