# Generated by Django 5.2.4 on 2026-03-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_favoriteestablishment_favoritemenuitem'),
        ('webapp', '0005_order_add_owner_dismissed'),
    ]

    operations = [
    ]
