# Generated by Django 5.2.4 on 2025-08-20 07:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_invitationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdminAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAdminCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAdminEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=255)),
                ('address_admin', models.TextField()),
                ('status_admin', models.CharField(default='Open', max_length=50)),
                ('image_admin', models.ImageField(blank=True, null=True, upload_to='admin_establishments/')),
                ('payment_methods_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities_admin', models.ManyToManyField(blank=True, to='webapp.newadminamenity')),
                ('category_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.newadmincategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdminInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_admin', models.CharField(max_length=12, unique=True)),
                ('is_used_admin', models.BooleanField(default=False)),
                ('created_at_admin', models.DateTimeField(auto_now_add=True)),
                ('used_by_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.newadminestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdminMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=100)),
                ('price_admin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('image_admin', models.ImageField(blank=True, null=True, upload_to='admin_menu_images/')),
                ('is_available_admin', models.BooleanField(default=True)),
                ('establishment_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_menu_items', to='webapp.newadminestablishment')),
            ],
        ),
    ]
