# Generated by Django 5.2.4 on 2025-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_establishment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_unique', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='AdminDashboardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Establishment',
        ),
        migrations.RemoveField(
            model_name='foodestablishmentcode',
            name='food_establishment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='open_days',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='days_open',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FoodEstablishmentCode',
        ),
    ]
