# Generated by Django 5.2.4 on 2026-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_orderitem_addons_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='custom_payment_policy',
            field=models.TextField(blank=True, help_text='Optional. Additional order/payment policy notes shown to customers during checkout (e.g., refund rules, claim instructions, special store rules). Enter one policy point per line.', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='addons_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of selected add-on options [{id, name, additional_price, qty}]'),
        ),
    ]
