# Generated by Django 5.2.4 on 2025-08-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_newadminamenity_newadmincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newadminestablishment',
            name='amenities_admin',
        ),
        migrations.RemoveField(
            model_name='newadminestablishment',
            name='category_admin',
        ),
        migrations.RemoveField(
            model_name='newadminmenuitem',
            name='establishment_admin',
        ),
        migrations.RemoveField(
            model_name='newadmininvitationcode',
            name='used_by_admin',
        ),
        migrations.DeleteModel(
            name='NewAdminAmenity',
        ),
        migrations.DeleteModel(
            name='NewAdminCategory',
        ),
        migrations.DeleteModel(
            name='NewAdminMenuItem',
        ),
        migrations.DeleteModel(
            name='NewAdminEstablishment',
        ),
        migrations.DeleteModel(
            name='NewAdminInvitationCode',
        ),
    ]
