# Generated by Django 5.2.4 on 2026-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_foodestablishment_custom_payment_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='gcash_number',
            field=models.CharField(blank=True, help_text="Owner's GCash mobile number (e.g., 09XXXXXXXXX). Used to generate a GCash QR code shown to customers at checkout.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodestablishment',
            name='custom_payment_policy',
            field=models.TextField(blank=True, help_text='The order/payment policy shown to customers during checkout (e.g., cancellation rules, refund rules, claim instructions, packaging fees). Enter one policy point per line. If left blank, no policy is shown to customers.', null=True),
        ),
    ]
