# Generated by Django 5.2.4 on 2025-08-20 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEstablishmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminCategory',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='days_open',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='open_days',
            field=models.ManyToManyField(blank=True, to='webapp.day'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='foodestablishmentcode',
            name='food_establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.foodestablishment'),
        ),
        migrations.DeleteModel(
            name='AdminDashboardProfile',
        ),
    ]
