# Generated by Django 5.2.4 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_foodestablishment_gcash_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot uploaded by customer as GCash payment proof.', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer submitted payment proof.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('to_pay', 'To Pay'), ('verifying', 'Verifying Payment'), ('preparing', 'Preparing'), ('to_claim', 'To Claim'), ('completed', 'Completed'), ('order_received', 'Order Received'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='request', max_length=50),
        ),
    ]
