# Generated by Django 5.2.4 on 2025-08-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_newadminestablishment_amenities_admin_and_more'),
        ('webapp', '0009_foodestablishmentcode_paymentmethod_and_more'),
    ]

    operations = [
    ]
