# Generated by Django 5.2.4 on 2025-08-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
