# Generated by Django 5.2.4 on 2025-08-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_foodestablishment_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='last_updated',
        ),
    ]
