# Generated by Django 5.2.4 on 2025-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_foodestablishment_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
