# Generated by Django 5.2.4 on 2025-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_foodestablishment_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
