# Generated by Django 5.2.4 on 2025-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_foodestablishment_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='unique_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
