# Generated by Django 5.2.4 on 2025-08-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_foodestablishment_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='unique_code',
        ),
    ]
