# Generated by Django 5.2.4 on 2025-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_foodestablishment_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
