# Generated by Django 5.2.4 on 2025-09-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_foodestablishment_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='disabled',
        ),
    ]
