# Generated by Django 5.2.4 on 2025-09-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_foodestablishment_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
