# Generated by Django 5.2.4 on 2025-09-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_foodestablishment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='is_active',
        ),
    ]
