# Generated by Django 5.2.4 on 2025-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_foodestablishment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
