# Generated by Django 5.2.4 on 2025-09-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_cart_is_active_cart_updated_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
