# Generated by Django 5.2.4 on 2025-10-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
