# Generated by Django 5.2.4 on 2025-10-13 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_remove_message_conversation_remove_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='features',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='open_days',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='website',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
