# Generated by Django 5.2.4 on 2025-10-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_otp_remove_foodestablishment_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_images/'),
        ),
    ]
