# Generated by Django 5.2.4 on 2025-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_foodestablishment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='image',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_cover/'),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_profile/'),
        ),
    ]
