# Generated by Django 5.2.4 on 2025-10-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_remove_foodestablishment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_images/'),
        ),
    ]
