# Generated by Django 5.2.4 on 2025-10-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_remove_foodestablishment_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/'),
        ),
    ]
