# Generated by Django 5.2.4 on 2025-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_foodestablishment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodestablishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishment_images/'),
        ),
    ]
