# Generated by Django 5.2.4 on 2025-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='foodestablishment',
            name='payment_methods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
