# Generated by Django 5.2.4 on 2025-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_foodestablishment_payment_methods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
