# Generated by Django 5.2.4 on 2025-10-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_alter_menuitem_options_menuitem_created_at_and_more'),
    ]

    operations = [
    ]
