# Generated by Django 5.2.4 on 2025-10-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_add_created_updated_to_menuitem'),
    ]

    operations = [
    ]
