# Generated by Django 5.2.4 on 2025-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_add_created_updated_to_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_payment_method',
            field=models.CharField(default='gcash', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='gcash_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
