# Generated by Django 5.2.4 on 2025-10-25 09:41

import django.db.models.deletion
import django.utils.timezone  # <--- IMPORT ADDED FOR THE FIX
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0045_order_gcash_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-is_top_seller', '-top_seller_marked_at', 'name'], 'verbose_name': 'Menu Item',
                     'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymongo_checkout_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            # --- THIS IS THE FIX ---
            # Changed default=1 to default=django.utils.timezone.now
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # --- FIX FOR "duplicate column" ERROR ---
        # This column was already added in the previously failed migration.
        # We comment it out to skip this step and apply the rest of the migration.
        # migrations.AddField(
        #     model_name='menuitem',
        #     name='top_seller_marked_at',
        #     field=models.DateTimeField(blank=True, default=None, null=True),
        # ),

        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock'),
        ),
        # --- THIS DUPLICATE OPERATION WAS REMOVED ---
        # migrations.AlterField(
        #     model_name='menuitem',
        #     name='top_seller_marked_at',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                    to='webapp.foodestablishment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gcash_payment_method',
            field=models.CharField(default='gcash_paymongo', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='gcash_reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'),
                         ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Completed')],
                db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_set',
                                    to='webapp.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='webapp_orde_user_id_ba223f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['establishment', 'status'], name='webapp_orde_establi_41b925_idx'),
        ),
    ]

