# Generated by Django 5.2.4 on 2025-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_hidden_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
