# Generated by Django 5.2.4 on 2025-12-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_alter_otp_options_otp_attempts_otp_is_verified'),
    ]

    operations = [
    ]
