# Generated by Django 5.2.4 on 2025-12-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_auto_20251206_1921'),
    ]

    operations = [
    ]
